name: Diskuise
version: '${project.version}'
main: me.tud.diskuise.Diskuise
api-version: 1.16
softdepend: [ Skript, LibsDisguises, ProtocolLib ]
authors: [ _tud ]
description: A simple Skript addon for disguising players/entities into other entities
website: https://github.com/UnderscoreTud/diskuise
